project_id = "swfshqvvbohnahdyndch"

[functions.ai-suggest-response]
verify_jwt = false

[functions.ai-copilot-chat]
verify_jwt = false

[functions.ai-analyze-conversation]
verify_jwt = false

[functions.ai-generate-summary]
verify_jwt = false

[functions.save-attendance-data]
verify_jwt = true

[functions.evolution-test-connection]
verify_jwt = false

[functions.evolution-create-instance]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.evolution-send-message]
verify_jwt = false

[functions.evolution-check-connection]
verify_jwt = false

[functions.uzapi-webhook-refactor]
verify_jwt = false

[functions.uzapi-webhook]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.webhook-queue-receiver]
verify_jwt = false

[functions.webhook-queue-processor]
verify_jwt = false

[functions.webhook-handle-message]
verify_jwt = false

[functions.webhook-handle-status]
verify_jwt = false

[functions.send-push]
verify_jwt = false
