project_id = "swfshqvvbohnahdyndch"

[functions.ai-suggest-response]
verify_jwt = false

[functions.ai-copilot-chat]
verify_jwt = false

[functions.evolution-test-connection]
verify_jwt = false

[functions.evolution-create-instance]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.evolution-send-message]
verify_jwt = false

[functions.evolution-check-connection]
verify_jwt = false